development:
  adapter: postgresql
  encoding: unicode
  database: beta_list_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: beta_list_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: beta_list_production
  pool: 5
  host: localhost
